export const SET_LOADING = 'SET_LOADING';
export const GET_RABOTA_PREVIEW = 'GET_RABOTA_PREVIEW';
export const GET_RABOTA_VACANCY = 'GET_RABOTA_VACANCY';
export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
